# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'
  - script: |
      npm run lint
    displayName: 'Runs linting checks'
  - script: |
      npm test
    displayName: 'Runs tests'
  - script: |
      npm run import:samples
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

    displayName: 'Imports samples'
  - script: |
      npm run import:loc-strings
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    displayName: 'Imports loc-strings'

  - script: |
      npm run build:prod
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    displayName: 'Runs a production build'


  - task: AzureFileCopy@2
    inputs:
      sourcePath: 'dist'
      azureConnectionType: 'ConnectedServiceNameARM'
      azureSubscription: 'arm-connection'
      destination: 'azureBlob'
      storage: 'graphstagingblobstorage'
      containerName: 'staging/vendor/bower_components/explorer/dist'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    displayName: 'Stage'

